from pathlib import Path
p=Path('app_mlb.py'); s=p.read_text(encoding='utf-8'); orig=s
marker='''def calcular_criterio_kelly(probabilidad_real, cuota_decimal, fraccion=0.25):\n'''
helper='''@st.cache_data(ttl=3600)\ndef _load_bullpen_proxy():\n    try:\n        path='data/mlb_bullpen.csv'\n        if not os.path.exists(path):\n            return pd.DataFrame()\n        df=pd.read_csv(path)\n        if df.empty or 'Team' not in df.columns or 'ERA' not in df.columns:\n            return pd.DataFrame()\n        df['ERA']=pd.to_numeric(df['ERA'],errors='coerce')\n        if 'Season' in df.columns:\n            df['Season']=pd.to_numeric(df['Season'],errors='coerce')\n        return df.dropna(subset=['Team','ERA'])\n    except Exception:\n        return pd.DataFrame()\n\n\ndef _bullpen_era(team, fallback):\n    try:\n        df=_load_bullpen_proxy()\n        rows=df[df['Team'].astype(str).str.upper()==str(team).upper()]\n        if rows.empty:\n            return float(fallback)\n        if 'Season' in rows.columns:\n            rows=rows.sort_values('Season')\n        return float(rows.iloc[-1]['ERA'])\n    except Exception:\n        return float(fallback)\n\n\n'''
if 'def _bullpen_era(' not in s:
    s=s.replace(marker,helper+marker,1)
old='''                            team_bullpen_loc = df_pit[df_pit['Team'] == loc_abbr]\n                            bullpen_loc_era = float(team_bullpen_loc.iloc[-1]['ERA']) if not team_bullpen_loc.empty else 4.0\n                            \n                            team_bullpen_vis = df_pit[df_pit['Team'] == vis_abbr]\n                            bullpen_vis_era = float(team_bullpen_vis.iloc[-1]['ERA']) if not team_bullpen_vis.empty else 4.0\n'''
new='''                            team_bullpen_loc = df_pit[df_pit['Team'] == loc_abbr]\n                            team_era_loc = float(team_bullpen_loc.iloc[-1]['ERA']) if not team_bullpen_loc.empty else 4.0\n                            bullpen_loc_era = _bullpen_era(loc_abbr, team_era_loc)\n                            \n                            team_bullpen_vis = df_pit[df_pit['Team'] == vis_abbr]\n                            team_era_vis = float(team_bullpen_vis.iloc[-1]['ERA']) if not team_bullpen_vis.empty else 4.0\n                            bullpen_vis_era = _bullpen_era(vis_abbr, team_era_vis)\n'''
if old not in s: raise SystemExit('scanner bullpen marker missing')
s=s.replace(old,new,1)
old2='''                    team_bullpen_loc = df_pit[df_pit['Team'] == loc_abbr]\n                    bullpen_loc_era = float(team_bullpen_loc.iloc[-1]['ERA']) if not team_bullpen_loc.empty else 4.0\n                    \n                    team_bullpen_vis = df_pit[df_pit['Team'] == vis_abbr]\n                    bullpen_vis_era = float(team_bullpen_vis.iloc[-1]['ERA']) if not team_bullpen_vis.empty else 4.0\n'''
new2='''                    team_bullpen_loc = df_pit[df_pit['Team'] == loc_abbr]\n                    team_era_loc = float(team_bullpen_loc.iloc[-1]['ERA']) if not team_bullpen_loc.empty else 4.0\n                    bullpen_loc_era = _bullpen_era(loc_abbr, team_era_loc)\n                    \n                    team_bullpen_vis = df_pit[df_pit['Team'] == vis_abbr]\n                    team_era_vis = float(team_bullpen_vis.iloc[-1]['ERA']) if not team_bullpen_vis.empty else 4.0\n                    bullpen_vis_era = _bullpen_era(vis_abbr, team_era_vis)\n'''
if old2 not in s: raise SystemExit('individual bullpen marker missing')
s=s.replace(old2,new2,1)
if s==orig: raise SystemExit('no changes')
for x in ['def _bullpen_era(', '_bullpen_era(loc_abbr, team_era_loc)', '_bullpen_era(vis_abbr, team_era_vis)']:
    if x not in s: raise SystemExit(f'missing {x}')
p.write_text(s,encoding='utf-8'); print('bullpen app patch applied')
